// apps/web/components/ide/agent/AgentManager.tsx
"use client";

/**
 * Agent Manager: substitui o antigo histórico "escolher tarefa passada para
 * repreencher o prompt" por uma grade de cards com status, cobrindo tanto as
 * sessões vivas nesta aba (via `useAgentSessions`) quanto o histórico
 * persistido no backend — clicar numa sessão encerrada carrega o transcript
 * real (`/messages`), não só o texto da tarefa.
 */

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  getAgentGraph,
  listAgentSessions,
  type AgentLiveStatus,
  type AgentSessionRecord as SessionRecord,
} from "@/lib/api/agent";
import { fuzzyScore } from "@/lib/ide-store";
import type { SessionStatus, SessionSummary } from "./sessionTypes";

interface Row {
  id: string;
  task: string;
  mode: string;
  branch: string;
  status: SessionStatus;
  updatedAt: string | null;
  parentId: string | null;
}

// Status ao vivo do AgentCoordinator (ADR 0004) só existe para sessões que
// passaram por spawn_agent — mapeado pro mesmo enum de sempre pra não
// precisar de pill/CSS novo. `waiting_for_message` cai em "running": pro
// usuário, um filho esperando resposta ainda está ativo, a distinção que
// importa de verdade é "esperando aprovação humana".
const LIVE_STATUS_MAP: Record<AgentLiveStatus, SessionStatus> = {
  running: "running",
  waiting_for_message: "running",
  waiting_approval: "awaiting-approval",
  completed: "done",
  failed: "error",
  stopped: "closed",
};

const STATUS_LABEL: Record<SessionStatus, string> = {
  running: "rodando",
  "awaiting-approval": "aguardando aprovação",
  done: "concluída",
  error: "erro",
  closed: "encerrada",
};

function tempoRelativo(iso: string): string {
  const diffMs = Date.now() - new Date(iso).getTime();
  const min = Math.round(diffMs / 60000);
  if (min < 1) return "agora";
  if (min < 60) return `${min}min`;
  const h = Math.round(min / 60);
  if (h < 24) return `${h}h`;
  return `${Math.round(h / 24)}d`;
}

export function AgentManager({
  project,
  refreshKey,
  liveSessions,
  activeId,
  onOpenLive,
  onOpenClosed,
  onClose,
}: {
  project: string | null;
  refreshKey: number;
  liveSessions: SessionSummary[];
  activeId: string | null;
  onOpenLive: (sessionId: string) => void;
  onOpenClosed: (sessionId: string, task: string) => void;
  onClose: () => void;
}) {
  const [historico, setHistorico] = useState<SessionRecord[]>([]);
  const [query, setQuery] = useState("");
  const [erro, setErro] = useState<string | null>(null);
  const [carregando, setCarregando] = useState(false);
  const [liveStatusById, setLiveStatusById] = useState<Map<string, SessionStatus>>(new Map());

  const carregar = useCallback(async () => {
    if (!project) return;
    setCarregando(true);
    try {
      const sessions = await listAgentSessions(project, 50);
      setHistorico(sessions);
      setErro(null);
    } catch (err) {
      setErro(err instanceof Error ? err.message : String(err));
    } finally {
      setCarregando(false);
    }
  }, [project]);

  useEffect(() => {
    void carregar();
  }, [carregar, refreshKey]);

  const liveById = useMemo(() => new Map(liveSessions.map((s) => [s.id, s])), [liveSessions]);

  // Raízes com pelo menos um filho no histórico (orquestração multiagente,
  // ADR 0004) ganham uma consulta ao AgentCoordinator pra saber se algum
  // descendente está `waiting_approval` — a lista de sessões sozinha não
  // revela isso pra um filho headless que nunca abriu SSE nesta aba.
  useEffect(() => {
    const raizesComFilhos = new Set(
      historico.filter((r) => r.parent_session_id).map((r) => r.parent_session_id as string),
    );
    if (raizesComFilhos.size === 0) {
      setLiveStatusById(new Map());
      return;
    }
    let cancelado = false;
    Promise.all(
      [...raizesComFilhos].map((raiz) => getAgentGraph(raiz).catch(() => [])),
    ).then((arvores) => {
      if (cancelado) return;
      const mapa = new Map<string, SessionStatus>();
      for (const no of arvores.flat()) {
        mapa.set(no.session_id, LIVE_STATUS_MAP[no.status]);
      }
      setLiveStatusById(mapa);
    });
    return () => {
      cancelado = true;
    };
  }, [historico]);

  const rows = useMemo<Row[]>(() => {
    const vistos = new Set<string>();
    const linhas: Row[] = [];

    // Sessões vivas nesta aba primeiro — são as mais relevantes agora.
    for (const s of liveSessions) {
      vistos.add(s.id);
      const registro = historico.find((r) => r.session_id === s.id);
      linhas.push({
        id: s.id,
        task: s.task,
        mode: registro?.mode ?? "",
        branch: s.branch || registro?.branch || "",
        status: liveStatusById.get(s.id) ?? s.status,
        updatedAt: registro?.updated_at ?? null,
        parentId: registro?.parent_session_id ?? null,
      });
    }

    for (const r of historico) {
      if (vistos.has(r.session_id)) continue;
      linhas.push({
        id: r.session_id,
        task: r.task,
        mode: r.mode,
        branch: r.branch ?? "",
        // `live` aqui é "rodando em algum processo do backend", não
        // necessariamente nesta aba — tratamos como encerrada para o clique
        // recair em "carregar transcript", que funciona nos dois casos.
        status: liveStatusById.get(r.session_id) ?? (r.status === "closed" ? "closed" : r.live ? "running" : "closed"),
        updatedAt: r.updated_at,
        parentId: r.parent_session_id,
      });
    }

    return linhas;
  }, [liveSessions, historico, liveStatusById]);

  // Sem busca: ordem de árvore (pai, depois seus filhos recursivamente,
  // depois a próxima raiz) — é assim que orquestração multiagente (ADR
  // 0004) fica visível sem precisar abrir GET /api/agent/sessions na mão.
  const arvore = useMemo<(Row & { depth: number })[]>(() => {
    const idsPresentes = new Set(rows.map((r) => r.id));
    const filhosDe = new Map<string | null, Row[]>();
    for (const r of rows) {
      // Pai fora da janela dos últimos 50 registros (ou de outro projeto):
      // trata como raiz em vez de esconder a linha.
      const pai = r.parentId && idsPresentes.has(r.parentId) ? r.parentId : null;
      if (!filhosDe.has(pai)) filhosDe.set(pai, []);
      filhosDe.get(pai)!.push(r);
    }
    const resultado: (Row & { depth: number })[] = [];
    const visitar = (pai: string | null, depth: number) => {
      for (const r of filhosDe.get(pai) ?? []) {
        resultado.push({ ...r, depth });
        visitar(r.id, depth + 1);
      }
    };
    visitar(null, 0);
    return resultado;
  }, [rows]);

  // Com busca: lista plana ordenada por score — indentação só faz sentido
  // navegando a árvore inteira, não um recorte filtrado dela.
  const filtradas = useMemo<(Row & { depth: number })[]>(() => {
    if (!query.trim()) return arvore;
    return rows
      .map((r) => ({ r, score: fuzzyScore(r.task, query) }))
      .filter((x): x is { r: Row; score: number } => x.score !== null)
      .sort((a, b) => b.score - a.score)
      .map(({ r }) => ({ ...r, depth: 0 }));
  }, [arvore, rows, query]);

  if (!project) return null;

  return (
    <div className="agent-session-list">
      <div className="agent-session-list-search">
        <input
          value={query}
          placeholder="Buscar sessões…"
          onChange={(e) => setQuery(e.target.value)}
          autoFocus
        />
        <button type="button" className="icon-action-btn" onClick={onClose} title="Fechar Agent Manager">
          ×
        </button>
      </div>

      {erro && <div className="panel-error">{erro}</div>}
      {carregando && rows.length === 0 && <div className="tree-hint">carregando…</div>}
      {!carregando && filtradas.length === 0 && !erro && (
        <div className="tree-hint">
          {rows.length === 0 ? "Nenhuma sessão neste projeto ainda." : `Nenhuma sessão corresponde a "${query}". `}
          {rows.length > 0 && (
            <button type="button" className="text-btn-inline" onClick={() => setQuery("")}>
              Redefinir filtro
            </button>
          )}
        </div>
      )}

      <div className="agent-session-items">
        {filtradas.map((r) => {
          const isLive = liveById.has(r.id);
          return (
            <button
              key={r.id}
              type="button"
              className={`agent-session-item${r.id === activeId ? " active" : ""}`}
              style={r.depth > 0 ? { marginLeft: Math.min(r.depth, 3) * 16 } : undefined}
              title={isLive ? "Trocar para esta sessão" : "Abrir o transcript desta sessão"}
              onClick={() => (isLive ? onOpenLive(r.id) : onOpenClosed(r.id, r.task))}
            >
              <div className="agent-session-item-top">
                {r.depth > 0 && (
                  <span className="agent-session-item-child-marker" title="Agente filho (spawn_agent)">
                    ↳
                  </span>
                )}
                <span className={`session-status-pill ${r.status}`}>{STATUS_LABEL[r.status]}</span>
                <span className="agent-session-item-task">{r.task}</span>
              </div>
              <div className="agent-session-item-meta">
                <span>{r.branch || "sem branch"}</span>
                {r.mode && <span>{r.mode}</span>}
                {r.updatedAt && <span>{tempoRelativo(r.updatedAt)}</span>}
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );
}

// apps/desktop/src/lib/components/AgentManager.svelte
<script lang="ts">
  /**
   * Agent Manager do Lite — porta simplificada de
   * `apps/web/components/ide/agent/AgentManager.tsx`.
   *
   * Lista as sessões do projeto (vivas nesta aba + histórico persistido) numa
   * árvore por `parent_session_id` (spawn_agent, ADR 0004). Diferença
   * deliberada em relação ao hub: não consulta `getAgentGraph` para status ao
   * vivo de filhos headless — um filho que nunca abriu stream nesta aba
   * aparece com o status do último registro conhecido, não em tempo real.
   * Simplificação aceitável para um cliente "lite"; o hub continua sendo a
   * fonte de verdade para orquestração multiagente observada de perto.
   */
  import { onMount } from "svelte";
  import { listAgentSessions, type AgentSessionRecord } from "../api/agent";
  import type { SessionStatus, SessionSummary } from "../agent/sessionTypes";

  interface Row {
    id: string;
    task: string;
    mode: string;
    branch: string;
    status: SessionStatus;
    updatedAt: string | null;
    parentId: string | null;
    depth: number;
  }

  let { project = "", refreshKey = 0, liveSessions = [], activeId = null, onOpenLive, onOpenClosed, onClose } = $props<{
    project?: string;
    /** Incrementar de fora força um novo `GET /sessions` (ex.: após criar sessão). */
    refreshKey?: number;
    liveSessions?: SessionSummary[];
    activeId?: string | null;
    onOpenLive?: (sessionId: string) => void;
    onOpenClosed?: (sessionId: string, task: string) => void;
    onClose?: () => void;
  }>();

  const STATUS_LABEL: Record<SessionStatus, string> = {
    running: "rodando",
    "awaiting-approval": "aguardando aprovação",
    done: "concluída",
    error: "erro",
    closed: "encerrada",
  };

  let historico = $state<AgentSessionRecord[]>([]);
  let query = $state("");
  let erro = $state<string | null>(null);
  let carregando = $state(false);

  async function carregar() {
    if (!project) return;
    carregando = true;
    try {
      historico = await listAgentSessions(project, 50);
      erro = null;
    } catch (err) {
      erro = err instanceof Error ? err.message : String(err);
    } finally {
      carregando = false;
    }
  }

  onMount(carregar);
  $effect(() => {
    void refreshKey;
    void project;
    void carregar();
  });

  let liveIds = $derived(new Set(liveSessions.map((s: SessionSummary) => s.id)));

  let rows = $derived.by((): Omit<Row, "depth">[] => {
    const vistos = new Set<string>();
    const linhas: Omit<Row, "depth">[] = [];

    for (const s of liveSessions as SessionSummary[]) {
      vistos.add(s.id);
      const registro = historico.find((r) => r.session_id === s.id);
      linhas.push({
        id: s.id,
        task: s.task,
        mode: registro?.mode ?? "",
        branch: s.branch || registro?.branch || "",
        status: s.status,
        updatedAt: registro?.updated_at ?? null,
        parentId: registro?.parent_session_id ?? null,
      });
    }

    for (const r of historico) {
      if (vistos.has(r.session_id)) continue;
      linhas.push({
        id: r.session_id,
        task: r.task,
        mode: r.mode,
        branch: r.branch ?? "",
        status: r.status === "closed" ? "closed" : r.live ? "running" : "closed",
        updatedAt: r.updated_at,
        parentId: r.parent_session_id,
      });
    }

    return linhas;
  });

  // Sem busca: árvore (pai, filhos recursivamente, próxima raiz).
  let arvore = $derived.by((): Row[] => {
    const idsPresentes = new Set(rows.map((r) => r.id));
    const filhosDe = new Map<string | null, Omit<Row, "depth">[]>();
    for (const r of rows) {
      const pai = r.parentId && idsPresentes.has(r.parentId) ? r.parentId : null;
      if (!filhosDe.has(pai)) filhosDe.set(pai, []);
      filhosDe.get(pai)!.push(r);
    }
    const resultado: Row[] = [];
    const visitar = (pai: string | null, depth: number) => {
      for (const r of filhosDe.get(pai) ?? []) {
        resultado.push({ ...r, depth });
        visitar(r.id, depth + 1);
      }
    };
    visitar(null, 0);
    return resultado;
  });

  // Com busca: substring case-insensitive, lista plana (sem indentação de árvore).
  let filtradas = $derived.by((): Row[] => {
    const termo = query.trim().toLowerCase();
    if (!termo) return arvore;
    return rows
      .filter((r) => r.task.toLowerCase().includes(termo))
      .map((r) => ({ ...r, depth: 0 }));
  });

  function tempoRelativo(iso: string): string {
    const diffMs = Date.now() - new Date(iso).getTime();
    const min = Math.round(diffMs / 60000);
    if (min < 1) return "agora";
    if (min < 60) return `${min}min`;
    const h = Math.round(min / 60);
    if (h < 24) return `${h}h`;
    return `${Math.round(h / 24)}d`;
  }
</script>

<div class="agent-manager">
  <div class="manager-search">
    <input bind:value={query} placeholder="Buscar sessões…" />
    {#if onClose}
      <button type="button" class="btn-close-manager" onclick={() => onClose?.()} title="Fechar Agent Manager">
        ×
      </button>
    {/if}
  </div>

  {#if erro}
    <div class="manager-error">{erro}</div>
  {/if}
  {#if carregando && rows.length === 0}
    <div class="manager-hint">carregando…</div>
  {/if}
  {#if !carregando && filtradas.length === 0 && !erro}
    <div class="manager-hint">
      {rows.length === 0 ? "Nenhuma sessão neste projeto ainda." : `Nenhuma sessão corresponde a "${query}".`}
      {#if rows.length > 0}
        <button type="button" class="text-btn-inline" onclick={() => (query = "")}>Redefinir filtro</button>
      {/if}
    </div>
  {/if}

  <div class="manager-items">
    {#each filtradas as r (r.id)}
      <button
        type="button"
        class="manager-item {r.id === activeId ? 'active' : ''}"
        style={r.depth > 0 ? `margin-left: ${Math.min(r.depth, 3) * 16}px` : undefined}
        title={liveIds.has(r.id) ? "Trocar para esta sessão" : "Abrir o transcript desta sessão"}
        onclick={() => (liveIds.has(r.id) ? onOpenLive?.(r.id) : onOpenClosed?.(r.id, r.task))}
      >
        <div class="manager-item-top">
          {#if r.depth > 0}
            <span class="child-marker" title="Agente filho (spawn_agent)">↳</span>
          {/if}
          <span class="status-pill {r.status}">{STATUS_LABEL[r.status]}</span>
          <span class="manager-item-task">{r.task}</span>
        </div>
        <div class="manager-item-meta">
          <span>{r.branch || "sem branch"}</span>
          {#if r.mode}<span>{r.mode}</span>{/if}
          {#if r.updatedAt}<span>{tempoRelativo(r.updatedAt)}</span>{/if}
        </div>
      </button>
    {/each}
  </div>
</div>

<style>
  .agent-manager {
    display: flex;
    flex-direction: column;
    gap: 6px;
    padding: 8px;
    background: #18181b;
    border-bottom: 1px solid var(--border-color);
    max-height: 260px;
    overflow-y: auto;
  }
  .manager-search {
    display: flex;
    gap: 6px;
    align-items: center;
  }
  .manager-search input {
    flex: 1;
    background: var(--bg-dark);
    border: 1px solid var(--border-color);
    color: var(--text-main);
    border-radius: 4px;
    padding: 4px 8px;
    font-size: 0.78rem;
  }
  .manager-search input:focus {
    outline: none;
    border-color: var(--accent-cyan);
  }
  .btn-close-manager {
    background: transparent;
    border: none;
    color: var(--text-muted);
    font-size: 1rem;
    cursor: pointer;
    padding: 0 4px;
  }
  .manager-error {
    color: #fca5a5;
    font-size: 0.72rem;
  }
  .manager-hint {
    color: var(--text-muted);
    font-size: 0.72rem;
  }
  .text-btn-inline {
    background: none;
    border: none;
    color: var(--accent-cyan);
    cursor: pointer;
    text-decoration: underline;
    font-size: inherit;
    padding: 0;
  }
  .manager-items {
    display: flex;
    flex-direction: column;
    gap: 3px;
  }
  .manager-item {
    display: flex;
    flex-direction: column;
    gap: 2px;
    background: var(--bg-dark);
    border: 1px solid var(--border-color);
    border-radius: 4px;
    padding: 5px 8px;
    text-align: left;
    cursor: pointer;
    color: var(--text-main);
  }
  .manager-item:hover {
    border-color: var(--accent-cyan);
  }
  .manager-item.active {
    border-color: var(--accent-blue);
    background: #1e293b;
  }
  .manager-item-top {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 0.78rem;
  }
  .child-marker {
    color: var(--text-muted);
  }
  .manager-item-task {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    flex: 1;
  }
  .manager-item-meta {
    display: flex;
    gap: 8px;
    font-size: 0.65rem;
    color: var(--text-muted);
  }
  .status-pill {
    font-size: 0.62rem;
    font-weight: 700;
    padding: 1px 6px;
    border-radius: 8px;
    white-space: nowrap;
  }
  .status-pill.running {
    background: rgba(59, 130, 246, 0.2);
    color: #60a5fa;
  }
  .status-pill.awaiting-approval {
    background: rgba(245, 158, 11, 0.2);
    color: #fbbf24;
  }
  .status-pill.done {
    background: rgba(16, 185, 129, 0.2);
    color: #34d399;
  }
  .status-pill.error {
    background: rgba(239, 68, 68, 0.2);
    color: #f87171;
  }
  .status-pill.closed {
    background: rgba(148, 163, 184, 0.2);
    color: #94a3b8;
  }
</style>
